// Safety Engine for DorkAtlas
// Ensures all queries are educational and ethical

const PROHIBITED_KEYWORDS = [
  // Credentials & Authentication
  'password', 'passwd', 'pwd', 'login', 'credentials', 'apikey', 'api key',
  'secret key', 'access token', 'session cookie', 'auth token', 'private key',
  'database password', 'admin password', 'root password', 'ssh key',
  
  // Sensitive Information
  'medical record', 'ssn', 'social security', 'credit card', 'bank account',
  'personal address', 'home address', 'phone number', 'email address',
  'government id', 'passport number', 'driver license', 'financial record',
  
  // Infrastructure Enumeration
  'camera', 'webcam', 'router', 'iot device', 'scada', 'industrial control',
  'plc', 'modbus', 'exposed server', 'open port', 'vulnerable server',
  
  // Offensive Security
  'exploit', 'vulnerability', 'zero day', 'malware', 'ransomware',
  'phishing', 'botnet', 'ddos', 'hacking tool', 'crack', 'keylogger',
  'backdoor', 'trojan', 'rootkit',
  
  // Privacy Violations
  'dox', 'doxxing', 'stalk', 'track person', 'personal information',
  'private data', 'surveillance', 'spy on',
  
  // Hacking & Unauthorized Access
  'hack', 'bypass', 'compromise', 'pwn', 'brute force', 'sql injection',
  'xss', 'csrf', 'privilege escalation', 'unauthorized access',
  
  // Other prohibited
  'leaked database', 'data breach', 'dump', 'stolen data'
];

const CREDENTIAL_PATTERNS = [
  /password/i,
  /passwd/i,
  /api[_-]?key/i,
  /secret[_-]?key/i,
  /access[_-]?token/i,
  /private[_-]?key/i,
  /auth[_-]?token/i,
  /session[_-]?cookie/i,
  /login[_-]?credentials/i,
];

const PII_PATTERNS = [
  /\b\d{3}-\d{2}-\d{4}\b/, // SSN
  /\b\d{4}[ -]?\d{4}[ -]?\d{4}[ -]?\d{4}\b/, // Credit card
  /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b.*(password|login)/i,
];

const OFFENSIVE_PATTERNS = [
  /exploit/i,
  /hack(ing)?/i,
  /bypass/i,
  /compromise/i,
  /vulnerab/i,
  /malware/i,
  /ransom/i,
  /phish/i,
  /doxx/i,
];

export function containsSensitiveKeywords(query: string): boolean {
  const lowerQuery = query.toLowerCase();
  return PROHIBITED_KEYWORDS.some(keyword => lowerQuery.includes(keyword));
}

export function containsCredentialPatterns(query: string): boolean {
  return CREDENTIAL_PATTERNS.some(pattern => pattern.test(query));
}

export function containsPIIPatterns(query: string): boolean {
  return PII_PATTERNS.some(pattern => pattern.test(query));
}

export function containsOffensivePatterns(query: string): boolean {
  return OFFENSIVE_PATTERNS.some(pattern => pattern.test(query));
}

export function sanitizeInput(input: string): string {
  // Remove potentially dangerous characters while preserving search syntax
  return input
    .replace(/[<>]/g, '') // Remove HTML tags
    .replace(/javascript:/gi, '')
    .replace(/on\w+=/gi, '')
    .trim();
}

export function isAllowedQuery(query: string): { allowed: boolean; reason?: string } {
  const sanitized = sanitizeInput(query);
  
  if (!sanitized || sanitized.length < 2) {
    return { allowed: false, reason: "Query is too short" };
  }

  if (containsSensitiveKeywords(sanitized)) {
    return { allowed: false, reason: "Query contains prohibited keywords" };
  }

  if (containsCredentialPatterns(sanitized)) {
    return { allowed: false, reason: "Query contains credential-related patterns" };
  }

  if (containsPIIPatterns(sanitized)) {
    return { allowed: false, reason: "Query contains personal information patterns" };
  }

  if (containsOffensivePatterns(sanitized)) {
    return { allowed: false, reason: "Query contains offensive or prohibited patterns" };
  }

  // Check for length limits
  if (sanitized.length > 500) {
    return { allowed: false, reason: "Query exceeds maximum length" };
  }

  return { allowed: true };
}

export function validateSearchQuery(
  operators: string[],
  searchTerm: string
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const fullQuery = [...operators, searchTerm].join(' ').trim();

  const check = isAllowedQuery(fullQuery);
  if (!check.allowed) {
    errors.push(check.reason || "Query not allowed");
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

// Educational disclaimer for generated queries
export const SAFETY_DISCLAIMER = 
  "All queries generated by DorkAtlas are for educational and legitimate public information research only. " +
  "Users are responsible for complying with applicable laws and respecting privacy rights.";
